language: node_js
node_js:
- node

sudo: false

cache:
  yarn: true
  directories:
  - node_modules

script:
- yarn run lint
- yarn test

deploy:
  provider: npm
  email: email@atimmer.com
  api_key:
    secure: GLSi1WlNzLeI+D2nWvrDM/x6Xirf7BH+UTOaxBCftwu4tjxgkYOQ51OiFIu0FNSPhuS1cg/OuBIbNxLECvB7D/7t47dI/bomYQZQZskYBgvEpjF1h/GPVs96IUQAs1/yfZBXdqujev+/zxoY32y/GtR4w4BmlsvhUJ0+6yCVndLv1SJFI3ijKV6p4bRauijnZ+CHpNJ+N04GWf/x+kp6/EnQI7GS37NZPdAM4LqmPepTH/9NEOyLaY5XHHxUdagjRera75/6KTYgL6YdZ3Pq/4kcbbjM3pxVSSN/wo2S6C0U/ltRU1y41gslrM++xBzAK7fCtWD+oxMafxD8PG6eaafQ/5FJm/T1f8qn/jinF9C8weF678gz5k0+X2nQJGGpaLZDfUKeU4q7F6Y9uByMBsQwyxjX2Fv2QNaaJMhi/yUGmO7OI/PvrDm0n1w31NKhcWKGfiJglAebc3gatR9ELdyopZlfQRtGQBV2VSOuZvzfNTWH6cKS4EQd8zKWMOqVj1bmipKYlvpTrqZj5etIqayNe4gWIlaMZmWueJPiQMqbdc8r1NnrNdBaTtC91b5nNjPbz1Q+Mv4SAqHhy1Xtc1EDgApljNO30Ceoq1G+GefFkbVJXeOK5zVMVMsvOfUJl5wRiWNJUrhuIywiuIi1gMfBf0Ms2YLNOhwEEw2iS/M=
  on:
    tags: true
    repo: Yoast/passport-openid-connect-wordpress
notifications:
  slack:
    secure: W3StABr+AdcdQawTObK4nbsnn5nLrTTtZfVpD/GEN6gvSOQcykbGEC5+ceYg0jn5b4StDyCiTo5blEsrpVICFpYKc44+ogah+qaGRUfVRS/rpOvn4AueXTWn4JxhZzuxqKMiTmyW+MQG0uYM7sk7Q5S+15jj6ilkj4QATaBVNbY=
