language: node_js
node_js:
- node

sudo: false

cache:
  yarn: true
  directories:
  - node_modules

script:
- yarn run lint
- yarn test

deploy:
  provider: npm
  email: NPM_EMAIL
  api_key: NPM_API_KEY
  on:
    tags: true

notifications:
  slack:
    secure: W3StABr+AdcdQawTObK4nbsnn5nLrTTtZfVpD/GEN6gvSOQcykbGEC5+ceYg0jn5b4StDyCiTo5blEsrpVICFpYKc44+ogah+qaGRUfVRS/rpOvn4AueXTWn4JxhZzuxqKMiTmyW+MQG0uYM7sk7Q5S+15jj6ilkj4QATaBVNbY=

env:
  global:
    # NPM_EMAIL
    - secure: "XHR43TNFdOWL7UWJ4zcbdUkRC1IHZ2GnvgfGDP7qkijczsUU4vN/vhwbV2VNtWIyWjT/NOQw+mkhvZqjTK6es+WOmlnMIW8M94IS38Of240j58aOn3e8KhqtsEK7HtjrtoTZA3lnZJB11d5xVFusajdzrZERPJRh+Sfp56stDOIaLbdcAQfWnr75vDZG6uCXqcT9tHJatWTlpzDKeBb3SlWKFL3rXIfsy4jnO+C0AtZ+gZxUQQ1CIxC9W/HuocdCFQFAEuMsHK7S/ALfsG/1lU6c1aapHTnZM/C35OGJxXmENTVfRo1A/ZPLpDx2/nnGv90J2091OQFWepejqAtp8c66IPiaA7phaBArpoTvnkajvuR99YmQzDKZiPnUOhNyO53yZ0ipTczSev190FUHOhsK9vAKOT/80SSYlBmEuAHj4UpSSpaMoymG/PtA7BYKs9wjtYSLm04I8i1mDbmO2jUU/l4KmC223Mpo2EtShI3h9KIt7weZUAPIxPJv87/soY5WCj98ryesu8ghxxKVKKe8CNR/qROkEf1k0Q9LqZyhdb3afL1W2nVWzVms96ad0Y3H5f9GRRp4jSMJkEAfX+eFXbeHQGOZL/11eypZARp9eu5HvY3NKGLnvUiDIAOj7Qz+XDXDHbbEjQEbaCmuUTDd2xb5zz2b+L22LDbqZO8="

    # NPM_API_KEY
    - secure: "WTtNZdWtlEOhSJk9yoe78JejiDjOBjgTP+u7kHqPUMU8U8qCH0ZpIV1enMSaBR4zTDIQFz/ikr2Z7oQkUuQlacR8jqd1gqQtjkFMJkAWHJUUWXkqLXvKXUOutj4EAgvCPQ7J5M5LQxCUc2UghFxlS6q0f+LE98cRDE7puA0a/Qb8omrSu4vGcg2NrukyjiqwZmOeD4bdQPVzP7EjGpsNax0XCxOGTE1C0WRRy6fJ40If+Xm8iw+hYpj9xG950QEnRjG0gzgNQrkV8c5XbyqmtjOXWB/bhIYMkOEvBNyXWwujJqHSQ+rzrqVA0iTGrUL43wWFVlbCcc7s5olbGoPQFrnRkbnxgONhmUTrpzim0aS75G4HJTRR5k7p6gBu3e5yZIM1ManWrhbbkggFLSYqu1xrx9506CoU/+tjk6Xy5TXrmJ9GoG7h6ovo+z/Zp9kpLBTZQsBRyDSeQeRZ9cxhFUuT3PaWJbCksnA4kYTTG5HF49+YyTICG2D0nyQWa/UqFag0MwtJouM0o3/9LCHHTiRcSQjtFatk70n+Kr3b+4nnX7XhZOJpqkIperbMW0p5i0UA1fb4oeyEBAvwasxlxgSAHaenEEIhvA/vFUTDGJDQiulEBapD8n0113/CqZazjJ9dEX7+If+84MEq2LyEhfC85sfsyi999LygDj173NI="
